In [2]:
import json
import pandas as pd

In [3]:
with open("./data/hotels_korea_reviews_text.json", "r", encoding="utf-8") as file:
    data = file.read()
    ho = json.loads(data)

In [4]:
len(ho)

9027

# 호텔 인포 테이블

In [5]:
hi = []
nm = []
sr = []
rv = []
rt = []
cl = []
sv = []
co = []
cd = []
nh = []
rg = []
lo = []

In [6]:
for i in range(len(ho)):
    hotelid = ho[i]["data"]["common"]["injected_data"]["commonDataBlock"]["property"]["hotelId"]
    name = ho[i]["data"]["body"]["propertyDescription"]["name"]
    starRating = ho[i]["data"]["body"]["propertyDescription"]["starRating"]
    reviewsTotal = ho[i]["data"]["body"]["reviewContent"]["pagination"]["reviewsTotal"]
    rating = ho[i]["data"]["body"]["reviewContent"]["overall"]["rating"]
    cleanliness = ho[i]["data"]["body"]["reviewContent"]["overall"]["ratingAspects"].get("cleanliness", "none")
    service = ho[i]["data"]["body"]["reviewContent"]["overall"]["ratingAspects"].get("service", "none")
    comfort = ho[i]["data"]["body"]["reviewContent"]["overall"]["ratingAspects"].get("comfort", "none")
    condition = ho[i]["data"]["body"]["reviewContent"]["overall"]["ratingAspects"].get("condition", "none")
    neighbourhood = ho[i]["data"]["body"]["reviewContent"]["overall"]["ratingAspects"].get("neighbourhood", "none")
    locality = ho[i]["data"]["body"]["propertyDescription"]["address"]["locality"]
    region = ho[i]["data"]["body"]["propertyDescription"]["address"].get("region", "locality")
    
    
    hi.append(hotelid)
    nm.append(name)
    sr.append(starRating)
    rv.append(reviewsTotal)
    rt.append(rating)
    cl.append(cleanliness)
    sv.append(service)
    co.append(comfort)
    cd.append(condition)
    nh.append(neighbourhood)
    lo.append(locality)
    rg.append(region)

In [7]:
result = dict(Hotelid=hi, 호텔이름=nm, 호텔등급=sr, 총리뷰수=rv, 평점=rt, 청결도=cl, 서비스=sv, 편안함=co, 시설상태=cd, 주변환경=nh, 시도=lo, 지역=rg)

In [8]:
result_df = pd.DataFrame(result)
result_df

,Hotelid,호텔이름,호텔등급,총리뷰수,평점,청결도,서비스,편안함,시설상태,주변환경,시도,지역
0,1041793024,상상속의집 (SangSang Hotel),3.0,67,7.8,8.0,7.6,8.2,7.8,8.2,거제시,경상남도
1,1041793024,상상속의집 (SangSang Hotel),3.0,67,7.8,8.0,7.6,8.2,7.8,8.2,거제시,경상남도
2,1041793024,상상속의집 (SangSang Hotel),3.0,67,7.8,8.0,7.6,8.2,7.8,8.2,거제시,경상남도
3,589827,바다마루 제주 (Badamaru Jeju),2.5,20,8.4,9.0,8.4,8.6,8.4,5.0,서귀포시,제주특별자치도
4,589827,바다마루 제주 (Badamaru Jeju),2.5,20,8.4,9.0,8.4,8.6,8.4,5.0,서귀포시,제주특별자치도
...,...,...,...,...,...,...,...,...,...,...,...,...
9022,507669,호텔 토스카나 (Hotel Toscana),4.0,608,9.2,9.2,9.2,9.4,9.2,7.8,서귀포시,제주특별자치도
9023,507669,호텔 토스카나 (Hotel Toscana),4.0,608,9.2,9.2,9.2,9.4,9.2,7.8,서귀포시,제주특별자치도
9024,718356256,평창펜션하늘숲 (Pyeongchang The Sky Forest),3.0,3,7.4,8.6,8.0,6.6,7.4,6.0,평창군,강원도
9025,718356256,평창펜션하늘숲 (Pyeongchang The Sky Forest),3.0,3,7.4,8.6,8.0,6.6,7.4,6.0,평창군,강원도
9026,1344945952,호텔플레이 (Hotel play),2.5,3,6.6,6.6,6.6,6.6,6.6,none,창원시,경상남도

# 사용자 테이블

In [9]:
hi2 = []
rd2 = []
it2 = []
tt2 = []
ra2 = []
de2 = []

In [10]:
for i in range(len(ho)):
    for h in range(len(ho[i]["data"]["body"]["reviewContent"]["reviews"]["hermes"]["groups"])):
        for g in range(len(ho[i]["data"]["body"]["reviewContent"]["reviews"]["hermes"]["groups"][h]["items"])):
            hotelid2 = ho[i]["data"]["common"]["injected_data"]["commonDataBlock"]["property"]["hotelId"]
            reviewDate = ho[i]["data"]["body"]["reviewContent"]["reviews"]["hermes"]["groups"][h]["items"][g]["reviewDate"]
            itineraryId = ho[i]["data"]["body"]["reviewContent"]["reviews"]["hermes"]["groups"][h]["items"][g].get("itineraryId", "none")
            tripType = ho[i]["data"]["body"]["reviewContent"]["reviews"]["hermes"]["groups"][h]["items"][g]['tripType']
            rating2 = ho[i]["data"]["body"]["reviewContent"]["reviews"]["hermes"]["groups"][h]["items"][g]['rating']
            description = ho[i]["data"]["body"]["reviewContent"]["reviews"]["hermes"]["groups"][h]["items"][g]["description"]

            hi2.append(hotelid2)
            rd2.append(reviewDate)
            it2.append(itineraryId)
            tt2.append(tripType)
            ra2.append(rating2)
            de2.append(description)

In [11]:
result2 = dict(Hotelid2=hi2, 리뷰일=rd2, 고객id=it2, 여행타입=tt2, 평점=ra2, 리뷰=de2)

In [12]:
result2_df = pd.DataFrame(result2)
result2_df

,Hotelid2,리뷰일,고객id,여행타입,평점,리뷰
0,1041793024,2020년 11월 20일,72009037635503,family,10.0,주차가 객실당 한칸씩 차고가 있는게 굉장히 특이했으며 가장 편리했음.\n간혹 차에 ...
1,1041793024,2020년 11월 14일,9202656047317,family,10.0,1. 오션뷰\n - 남해안의 어느 숙박업소가 그렇듯이 오션뷰가 좋습니다. 이 호텔...
2,1041793024,2020년 8월 11일,9196559102828,other,10.0,커플이 다녀가기에 좋은 숙소. 프라이빗함과 뷰도 갖춘 좋은 곳
3,1041793024,2020년 8월 10일,9201554317978,other,8.0,"위치와 뷰는 정말 좋습니다. 개별주차장이 생각보다 쓰기 좋았습니다. 다만, 호텔보다..."
4,1041793024,2020년 8월 7일,9196473456283,family,8.0,스탠다드 이용했어요\n방마다 차고가 있어서 편하게 짐 옮겼네요\n제가 이용한 방에 ...
...,...,...,...,...,...,...
208480,718356256,2019년 1월 19일,8141646862293,family,8.0,Pyeongchang - The Sky Forest Review: \r\nServi...
208481,718356256,2018년 12월 29일,8159891951288,family,6.0,The check-in took some time as there were none...
208482,1344945952,2020년 9월 14일,9196902905665,business,8.0,
208483,1344945952,2020년 7월 13일,9201269638204,business,2.0,
208484,1344945952,2020년 5월 22일,9195821601150,with-friends,10.0,

In [20]:
result2_df.to_csv("호텔스닷컴리뷰.csv", encoding="utf-8-sig", index=False)

In [21]:
result_df.to_csv("호텔정보.csv", encoding="utf-8-sig", index=False)