In [9]:
import pandas as pd

In [10]:
# dataframe
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}
countries = pd.DataFrame(data)
countries = countries.set_index('country') # 인덱스 지정
countries

                population    area    capital
country
Belgium               11.3   30510   Brussels
France                64.3  671308      Paris
Germany               81.3  357050     Berlin
Netherlands           16.9   41526  Amsterdam
United Kingdom        64.9  244820     London

In [11]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Belgium to United Kingdom
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  5 non-null      float64
 1   area        5 non-null      int64
 2   capital     5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

---

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도를 의미하는 `density` 칼럼을 추가하세요. (주의: 현재 'population' 칼럼은 100만 단위로 표기되어 있습니다)  
  
</div>

In [12]:
countries['density'] = countries["population"]/countries["area"] * 1000000

In [13]:
countries

                population    area    capital     density
country
Belgium               11.3   30510   Brussels  370.370370
France                64.3  671308      Paris   95.783158
Germany               81.3  357050     Berlin  227.699202
Netherlands           16.9   41526  Amsterdam  406.973944
United Kingdom        64.9  244820     London  265.092721

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도가 300을 초과하는 국가(country)의 수도(capital)과 인구(population)을 선택해주세요.  
  
</div>

In [14]:
countries.loc[(countries['density'] > 300), ["capital", "population"]]

               capital  population
country
Belgium       Brussels        11.3
Netherlands  Amsterdam        16.9

<div class="alert alert-success">
    <b>EXERCISE</b>: 'density_ratio' 칼럼을 추가해주세요. (density_ratio = 인구밀도/평균 인구밀도)
</div>

In [15]:
countries['density_ratio'] = countries['density']/countries['density'].mean()

In [16]:
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 영국(United Kingdom)의 수도(capital)를 'Cambridge'로 변경해주세요.
</div>

In [17]:
countries.loc["United Kingdom", 'capital'] = "Cambridge"

In [18]:
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구 밀도가 100 초과, 300 미만인 국가들을 표시해주세요.  
</div>

In [19]:
countries.loc[(countries['density'] < 300) & (countries['density'] > 100)]

                population    area    capital     density  density_ratio
country
Germany               81.3  357050     Berlin  227.699202       0.833502
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도가 7글자 이상인 국가들을 표시해주세요. (힌트: string의 len( )를 사용하세요.)
</div>

In [103]:
countries[(countries['capital'].str.len() >= 7)]

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도에 'am' 이 포함되는 국가들을 표시해주세요. (힌트: string의 contains( )를 사용하세요.)
</div>

In [21]:
countries.loc[(countries['capital'].str.contains("am"))]

                population    area    capital     density  density_ratio
country
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

# 영화리뷰 데이터에서 자료 찾기

movie_title_data.tsv 읽어오기

https://drive.google.com/file/d/1cvBtLVyfhfodJK-BXWqBLcopyus9HOIc/view?usp=sharing

In [117]:
titles = pd.read_csv("./data/movie_title_data.tsv", )

C:\Users\Admin\AppData\Local\Temp\ipykernel_16372\132108640.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  titles = pd.read_table("./data/movie_title_data.tsv")

<div class="alert alert-success">
    <b>EXERCISE</b>: titles 데이터프레임에는 몇 개의 영화가 기록되어 있나요?
</div>

In [118]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         object
 5   startYear       object
 6   endYear         object
 7   runtimeMinutes  object
 8   genres          object
dtypes: object(9)
memory usage: 577.3+ MB

In [119]:
titles.columns

Index(['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult',
       'startYear', 'endYear', 'runtimeMinutes', 'genres'],
      dtype='object')

In [120]:
titles.value_counts("originalTitle")

originalTitle
Episode #1.1            41344
Episode #1.2            37283
Episode #1.3            35175
Episode #1.4            31782
Episode #1.5            28991
                        ...
öregHarcos                  1
öregHarcos II               1
über den Wolken             1
überRICH                    1
ülker Dankek Reklami        1
Name: count, Length: 4019695, dtype: int64

<div class="alert alert-success">
    <b>EXERCISE</b>: titles에서 가장 빠른 시기에 제작된 영화 두 개를 표시하세요.  힌트: .sort_values()
</div>

In [121]:
titles.loc[titles["startYear"] == "\\N"] = 0

In [122]:
titles["startYear"] = titles["startYear"].astype(int)

In [125]:
titles[titles['startYear'] !=0].sort_values(by='startYear')[:2]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
5329521,tt3155794,short,Passage de Venus,Passage de Venus,0,1874,\N,1,"Documentary,Short"
3488807,tt14495706,short,La Rosace Magique,La Rosace Magique,0,1877,\N,1,"Animation,Short"

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(title)이 "Hamlet"인 영화는 몇 개가 있나요?
</div>

In [27]:
titles[(titles["originalTitle"] == "Hamlet")]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
594,tt0000598,short,"Hamlet, Prince of Denmark",Hamlet,0,1907,\N,10,"Drama,Short"
876,tt0000886,movie,"Hamlet, Prince of Denmark",Hamlet,0,1910,\N,\N,Drama
1228,tt0001240,movie,Hamlet,Hamlet,0,1911,\N,\N,Drama
1229,tt0001241,short,Hamlet,Hamlet,0,1910,\N,20,"Drama,Short"
1230,tt0001242,short,Hamlet,Hamlet,0,1908,\N,\N,"Drama,Short"
...,...,...,...,...,...,...,...,...,...
7347169,tt7656792,tvEpisode,Hamlet,Hamlet,0,2017,\N,\N,Animation
7413345,tt7798632,movie,Hamlet,Hamlet,0,\N,\N,\N,Comedy
7476376,tt7934018,tvMovie,Hamlet,Hamlet,0,1983,\N,\N,Drama
7609545,tt8219328,tvMovie,Hamlet,Hamlet,0,2018,\N,191,Drama
8306453,tt9703966,movie,Hamlet,Hamlet,0,\N,\N,\N,Drama

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(title)이 "Treasure Island"인 영화를 제작년도(year)의 오름차순에 따라 표시하세요
</div>

In [133]:
titles[(titles["originalTitle"] == "Treasure Island") & titles["startYear"] != 0].sort_value(by="startYear")

AttributeError: 'DataFrame' object has no attribute 'sort_value'

<div class="alert alert-success">
    <b>EXERCISE</b>: 1950년에서 1959년 사이 몇 개의 영화가 만들어졌나요?(1950 <= 제작년도 <= 1959)
</div>

In [136]:
len(titles[(titles["startYear"] >= 1950) & (titles["startYear"] <= 1959)])

118649

# 타이타닉 자료에서 그룹별 연산하기

원격 DB에 접속해서 titanic 데이터베이스 안에 있는 p_info, t_info, survived 테이블을 불러와 합치고 아래의 문제를 풀어보세요.<br>
<id:kict00, pw:kict00, ip:221.155.18.165:3306, db:titanic>

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 상위 5개 행을 출력하세요.
</div>

In [52]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb
engine = create_engine("mysql+pymysql://kict12:kict12@221.155.18.165:3306/titanic")
conn = engine.connect()
passenger = pd.read_sql("p_info", con=conn)
ticket = pd.read_sql("t_info", con=conn)
survived = pd.read_sql("survived", con=conn)
joined_df = pd.merge(passenger, ticket, how="left", on="PassengerId")
joined_df2 = pd.merge(joined_df, survived, how="left", on="PassengerId")

In [53]:
joined_df2.head()

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 정보(info)를 출력하세요.
</div>

In [54]:
joined_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    object
 2   Sex          891 non-null    object
 3   Age          714 non-null    float64
 4   SibSp        891 non-null    int64
 5   Parch        891 non-null    int64
 6   Ticket       891 non-null    object
 7   Pclass       891 non-null    int64
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
 11  Survived     891 non-null    int64
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 기술통계(describe)를 확인하세요.
</div>

In [55]:
joined_df2.describe()

,PassengerId,Age,SibSp,Parch,Pclass,Fare,Survived
count,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,29.699118,0.523008,0.381594,2.308642,32.204208,0.383838
std,257.353842,14.526497,1.102743,0.806057,0.836071,49.693429,0.486592
min,1.000000,0.420000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,223.500000,20.125000,0.000000,0.000000,2.000000,7.910400,0.000000
50%,446.000000,28.000000,0.000000,0.000000,3.000000,14.454200,0.000000
75%,668.500000,38.000000,1.000000,0.000000,3.000000,31.000000,1.000000
max,891.000000,80.000000,8.000000,6.000000,3.000000,512.329200,1.000000

<div class="alert alert-success">
    <b>EXERCISE</b>: 처음 100명의 데이터를 출력하세요.
</div>

In [180]:
joined_df2.head(100)

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10
PassengerId,,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,32.00
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1,48.00
3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,36.00
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1,45.00
5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,45.00
6,"Moran, Mr. James",male,29.699118,0,0,330877,3,8.4583,Unknown,Q,0,NaN
7,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,1,51.8625,E46,S,0,64.00
8,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,3,21.0750,Unknown,S,0,12.00
9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,3,11.1333,Unknown,S,1,37.00
10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,2,30.0708,Unknown,C,1,24.00
11,"Sandstrom, Miss. Marguerite Rut",female,4.000000,1,1,PP 9549,3,16.7000,G6,S,1,14.00
12,"Bonnell, Miss. Elizabeth",female,58.000000,0,0,113783,1,26.5500,C103,S,1,68.00
13,"Saundercock, Mr. William Henry",male,20.000000,0,0,A/5. 2151,3,8.0500,Unknown,S,0,30.00
14,"Andersson, Mr. Anders Johan",male,39.000000,1,5,347082,3,31.2750,Unknown,S,0,49.00
15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.000000,0,0,350406,3,7.8542,Unknown,S,0,24.00
16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.000000,0,0,248706,2,16.0000,Unknown,S,1,65.00
17,"Rice, Master. Eugene",male,2.000000,4,1,382652,3,29.1250,Unknown,Q,0,12.00
18,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,2,13.0000,Unknown,S,1,NaN
19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.000000,1,0,345763,3,18.0000,Unknown,S,0,41.00
20,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,3,7.2250,Unknown,C,1,NaN
21,"Fynney, Mr. Joseph J",male,35.000000,0,0,239865,2,26.0000,Unknown,S,0,45.00
22,"Beesley, Mr. Lawrence",male,34.000000,0,0,248698,2,13.0000,D56,S,1,44.00
23,"McGowan, Miss. Anna ""Annie""",female,15.000000,0,0,330923,3,8.0292,Unknown,Q,1,25.00
24,"Sloper, Mr. William Thompson",male,28.000000,0,0,113788,1,35.5000,A6,S,1,38.00
25,"Palsson, Miss. Torborg Danira",female,8.000000,3,1,NaN,3,21.0750,Unknown,S,0,18.00
26,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.000000,1,5,347077,3,31.3875,Unknown,S,1,48.00
27,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,3,7.2250,Unknown,C,0,NaN
28,"Fortune, Mr. Charles Alexander",male,19.000000,3,2,19950,1,263.0000,C23 C25 C27,S,0,29.00
29,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,3,7.8792,Unknown,Q,1,NaN
30,"Todoroff, Mr. Lalio",male,29.699118,0,0,349216,3,7.8958,Unknown,S,0,NaN
31,"Uruchurtu, Don. Manuel E",male,40.000000,0,0,PC 17601,1,27.7208,Unknown,C,0,50.00
32,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,29.699118,1,0,PC 17569,1,146.5208,B78,C,1,NaN
33,"Glynn, Miss. Mary Agatha",female,29.699118,0,0,335677,3,7.7500,Unknown,Q,1,NaN
34,"Wheadon, Mr. Edward H",male,66.000000,0,0,C.A. 24579,2,10.5000,Unknown,S,0,76.00
35,"Meyer, Mr. Edgar Joseph",male,28.000000,1,0,PC 17604,1,82.1708,Unknown,C,0,38.00
36,"Holverson, Mr. Alexander Oskar",male,42.000000,1,0,113789,1,52.0000,Unknown,S,0,52.00
37,"Mamee, Mr. Hanna",male,29.699118,0,0,2677,3,7.2292,Unknown,C,1,NaN
38,"Cann, Mr. Ernest Charles",male,21.000000,0,0,A./5. 2152,3,8.0500,Unknown,S,0,31.00
39,"Vander Planke, Miss. Augusta Maria",female,18.000000,2,0,345764,3,18.0000,Unknown,S,0,28.00
40,"Nicola-Yarred, Miss. Jamila",female,14.000000,1,0,2651,3,11.2417,Unknown,C,1,24.00
41,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.000000,1,0,7546,3,9.4750,Unknown,S,0,50.00
42,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.000000,1,0,11668,2,21.0000,Unknown,S,0,37.00
43,"Kraeff, Mr. Theodor",male,29.699118,0,0,349253,3,7.8958,Unknown,C,0,NaN
44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.000000,1,2,SC/Paris 2123,2,41.5792,Unknown,C,1,13.00
45,"Devaney, Miss. Margaret Delia",female,19.000000,0,0,330958,3,7.8792,Unknown,Q,1,29.00
46,"Rogers, Mr. William John",male,29.699118,0,0,S.C./A.4. 23567,3,8.0500,Unknown,S,0,NaN
47,"Lennon, Mr. Denis",male,29.699118,1,0,370371,3,15.5000,Unknown,Q,0,NaN
48,"O'Driscoll, Miss. Bridget",female,29.699118,0,0,14311,3,7.7500,Unknown,Q,1,NaN
49,"Samaan, Mr. Youssef",male,29.699118,2,0,2662,3,21.6792,Unknown,C,0,NaN
50,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.000000,1,0,349237,3,17.8000,Unknown,S,0,28.00
51,"Panula, Master. Juha Niilo",male,7.000000,4,1,3101295,3,39.6875,Unknown,S,0,17.00
52,"Nosworthy, Mr. Richard Cater",male,21.000000,0,0,A/4. 39886,3,7.8000,Unknown,S,0,31.00
53,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.000000,1,0,PC 17572,1,76.7292,D33,C,1,59.00
54,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.000000,1,0,2926,2,26.0000,Unknown,S,1,39.00
55,"Ostby, Mr. Engelhart Cornelius",male,65.000000,0,1,113509,1,61.9792,B30,C,0,75.00
56,"Woolner, Mr. Hugh",male,29.699118,0,0,19947,1,35.5000,C52,S,1,NaN
57,"Rugg, Miss. Emily",female,21.000000,0,0,C.A. 31026,2,10.5000,Unknown,S,1,31.00
58,"Novel, Mr. Mansouer",male,28.500000,0,0,2697,3,7.2292,Unknown,C,0,38.50
59,"West, Miss. Constance Mirium",female,5.000000,1,2,C.A. 34651,2,27.7500,Unknown,S,1,15.00
60,"Goodwin, Master. William Frederick",male,11.000000,5,2,CA 2144,3,46.9000,Unknown,S,0,21.00
61,"Sirayanian, Mr. Orsen",male,22.000000,0,0,2669,3,7.2292,Unknown,C,0,32.00
62,"Icard, Miss. Amelie",female,38.000000,0,0,113572,1,80.0000,B28,None,1,48.00
63,"Harris, Mr. Henry Birkhardt",male,45.000000,1,0,36973,1,83.4750,C83,S,0,55.00
64,"Skoog, Master. Harald",male,4.000000,3,2,347088,3,27.9000,Unknown,S,0,14.00
65,"Stewart, Mr. Albert A",male,29.699118,0,0,PC 17605,1,27.7208,Unknown,C,0,NaN
66,"Moubarek, Master. Gerios",male,29.699118,1,1,2661,3,15.2458,Unknown,C,1,NaN
67,"Nye, Mrs. (Elizabeth Ramell)",female,29.000000,0,0,C.A. 29395,2,10.5000,F33,S,1,39.00
68,"Crease, Mr. Ernest James",male,19.000000,0,0,S.P. 3464,3,8.1583,Unknown,S,0,29.00
69,"Andersson, Miss. Erna Alexandra",female,17.000000,4,2,3101281,3,7.9250,Unknown,S,1,27.00
70,"Kink, Mr. Vincenz",male,26.000000,2,0,315151,3,8.6625,Unknown,S,0,36.00
71,"Jenkin, Mr. Stephen Curnow",male,32.000000,0,0,C.A. 33111,2,10.5000,Unknown,S,0,42.00
72,"Goodwin, Miss. Lillian Amy",female,16.000000,5,2,NaN,3,46.9000,Unknown,S,0,26.00
73,"Hood, Mr. Ambrose Jr",male,21.000000,0,0,S.O.C. 14879,2,73.5000,Unknown,S,0,31.00
74,"Chronopoulos, Mr. Apostolos",male,26.000000,1,0,2680,3,14.4542,Unknown,C,0,36.00
75,"Bing, Mr. Lee",male,32.000000,0,0,1601,3,56.4958,Unknown,S,1,42.00
76,"Moen, Mr. Sigurd Hansen",male,25.000000,0,0,348123,3,7.6500,F G73,S,0,35.00
77,"Staneff, Mr. Ivan",male,29.699118,0,0,349208,3,7.8958,Unknown,S,0,NaN
78,"Moutal, Mr. Rahamin Haim",male,29.699118,0,0,374746,3,8.0500,Unknown,S,0,NaN
79,"Caldwell, Master. Alden Gates",male,0.830000,0,2,248738,2,29.0000,Unknown,S,1,10.83
80,"Dowdell, Miss. Elizabeth",female,30.000000,0,0,364516,3,12.4750,Unknown,S,1,40.00
81,"Waelens, Mr. Achille",male,22.000000,0,0,345767,3,9.0000,Unknown,S,0,32.00
82,"Sheerlinck, Mr. Jan Baptist",male,29.000000,0,0,345779,3,9.5000,Unknown,S,1,39.00
83,"McDermott, Miss. Brigdet Delia",female,29.699118,0,0,330932,3,7.7875,Unknown,Q,1,NaN
84,"Carrau, Mr. Francisco M",male,28.000000,0,0,113059,1,47.1000,Unknown,S,0,38.00
85,"Ilett, Miss. Bertha",female,17.000000,0,0,SO/C 14885,2,10.5000,Unknown,S,1,27.00
86,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.000000,3,0,3101278,3,15.8500,Unknown,S,1,43.00
87,"Ford, Mr. William Neal",male,16.000000,1,3,W./C. 6608,3,34.3750,Unknown,S,0,26.00
88,"Slocovski, Mr. Selman Francis",male,29.699118,0,0,SOTON/OQ 392086,3,8.0500,Unknown,S,0,NaN
89,"Fortune, Miss. Mabel Helen",female,23.000000,3,2,NaN,1,263.0000,C23 C25 C27,S,1,33.00
90,"Celotti, Mr. Francesco",male,24.000000,0,0,343275,3,8.0500,Unknown,S,0,34.00
91,"Christmann, Mr. Emil",male,29.000000,0,0,343276,3,8.0500,Unknown,S,0,39.00
92,"Andreasson, Mr. Paul Edvin",male,20.000000,0,0,347466,3,7.8542,Unknown,S,0,30.00
93,"Chaffee, Mr. Herbert Fuller",male,46.000000,1,0,W.E.P. 5734,1,61.1750,E31,S,0,56.00
94,"Dean, Mr. Bertram Frank",male,26.000000,1,2,C.A. 2315,3,20.5750,Unknown,S,0,36.00
95,"Coxon, Mr. Daniel",male,59.000000,0,0,364500,3,7.2500,Unknown,S,0,69.00
96,"Shorney, Mr. Charles Joseph",male,29.699118,0,0,374910,3,8.0500,Unknown,S,0,NaN
97,"Goldschmidt, Mr. George B",male,71.000000,0,0,PC 17754,1,34.6542,A5,C,0,81.00
98,"Greenfield, Mr. William Bertram",male,23.000000,0,1,PC 17759,1,63.3583,D10 D12,C,1,33.00
99,"Doling, Mrs. John T (Ada Julia Bone)",female,34.000000,0,1,231919,2,23.0000,Unknown,S,1,44.00
100,"Kantor, Mr. Sinai",male,34.000000,1,0,244367,2,26.0000,Unknown,S,0,44.00

In [179]:
pd.set_option('display.max_rows', 100)

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스가 10~20인 데이터를 출력하세요.
</div>

In [58]:
joined_df2[10:21]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,3,16.7000,G6,S,1
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
12,13,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,3,8.0500,None,S,0
13,14,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,3,31.2750,None,S,0
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,3,7.8542,None,S,0
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,2,16.0000,None,S,1
16,17,"Rice, Master. Eugene",male,2.0,4,1,382652,3,29.1250,None,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,None,S,1
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,3,18.0000,None,S,0
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,None,C,1
20,21,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,2,26.0000,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 컬럼 이름을 모두 출력하세요.
</div>

In [61]:
joined_df2.columns

Index(['PassengerId', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Pclass', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='object')

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 shape를 확인하세요.
</div>

In [62]:
joined_df2.shape

(891, 12)

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age' 컬럼의 평균을 구하세요.
</div>

In [63]:
joined_df2["Age"].mean()

np.float64(29.69911764705882)

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Survived' 컬럼의 고유값을 확인하세요.
</div>

In [64]:
joined_df2['Survived'].unique()

array([0, 1])

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 30 이상인 승객만 출력하세요.
</div>

In [68]:
joined_df2.loc[joined_df2["Age"] >= 30]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
6,7,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,1,51.8625,E46,S,0
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,3,9.0000,None,S,0
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
881,882,"Markun, Mr. Johann",male,33.0,0,0,349257,3,7.8958,None,S,0
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,3,29.1250,None,Q,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별이 'female'이고 생존한 승객만 출력하세요.
</div>

In [70]:
joined_df2.loc[(joined_df2["Sex"] == "female") & (joined_df2["Survived"] == 1)]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,3,11.1333,None,S,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,2,30.0708,None,C,1
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,2,24.0000,None,C,1
875,876,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,3,7.2250,None,C,1
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,2,26.0000,None,S,1
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 10살 이하이고 요금이 20 이상인 승객을 출력하세요.
</div>

In [71]:
joined_df2.loc[(joined_df2["Age"]  <= 10) & (joined_df2["Fare"] >= 20)]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
7,8,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,3,21.0750,None,S,0
16,17,"Rice, Master. Eugene",male,2.00,4,1,382652,3,29.1250,None,Q,0
24,25,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,3,21.0750,None,S,0
43,44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,2,41.5792,None,C,1
50,51,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,3,39.6875,None,S,0
58,59,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,2,27.7500,None,S,1
63,64,"Skoog, Master. Harald",male,4.00,3,2,347088,3,27.9000,None,S,0
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,None,S,1
119,120,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,3,31.2750,None,S,0
147,148,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,W./C. 6608,3,34.3750,None,S,0
164,165,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,3,39.6875,None,S,0
165,166,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,3,20.5250,None,S,1
171,172,"Rice, Master. Arthur",male,4.00,4,1,382652,3,29.1250,None,Q,0
182,183,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,3,31.3875,None,S,0
183,184,"Becker, Master. Richard F",male,1.00,2,1,230136,2,39.0000,F4,S,1
184,185,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,3,22.0250,None,S,1
193,194,"Navratil, Master. Michel M",male,3.00,1,1,230080,2,26.0000,F2,S,1
233,234,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,3,31.3875,None,S,1
237,238,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,2,26.2500,None,S,1
261,262,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,3,31.3875,None,S,1
278,279,"Rice, Master. Eric",male,7.00,4,1,382652,3,29.1250,None,Q,0
297,298,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,1,151.5500,C22 C26,S,0
305,306,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,1,151.5500,C22 C26,S,1
340,341,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,2,26.0000,F2,S,1
374,375,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,3,21.0750,None,S,0
386,387,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,3,46.9000,None,S,0
419,420,"Van Impe, Miss. Catharina",female,10.00,0,2,345773,3,24.1500,None,S,0
445,446,"Dodge, Master. Washington",male,4.00,0,2,33638,1,81.8583,A34,S,1
480,481,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,3,46.9000,None,S,0
530,531,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,2,26.0000,None,S,1
535,536,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,2,26.2500,None,S,1
541,542,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,3,31.2750,None,S,0
549,550,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,2,36.7500,None,S,1
618,619,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,2,39.0000,F4,S,1
634,635,"Skoog, Miss. Mabel",female,9.00,3,2,347088,3,27.9000,None,S,0
642,643,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,3,27.9000,None,S,0
720,721,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,2,33.0000,None,S,1
750,751,"Wells, Miss. Joan",female,4.00,1,1,29103,2,23.0000,None,S,1
787,788,"Rice, Master. George Hugh",male,8.00,4,1,382652,3,29.1250,None,Q,0
788,789,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,3,20.5750,None,S,1
813,814,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,3,31.2750,None,S,0
819,820,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,3,27.9000,None,S,0
824,825,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,3,39.6875,None,S,0
827,828,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,2,37.0042,None,C,1
850,851,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,3,31.2750,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 결측치인 데이터를 출력하세요.
</div>

In [74]:
joined_df2.loc[(joined_df2["Age"].isna() == 1)]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
5,6,"Moran, Mr. James",male,NaN,0,0,330877,3,8.4583,None,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,None,S,1
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,None,C,1
26,27,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,3,7.2250,None,C,0
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,3,7.8792,None,Q,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,None,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,None,S,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,None,S,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,None,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이를 기준으로 오름차순 정렬하세요.
</div>

In [85]:
joined_df2.sort_values('Age')

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
803,804,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,3,8.5167,None,C,1
755,756,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,2,14.5000,None,S,1
469,470,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,3,19.2583,None,C,1
644,645,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,3,19.2583,None,C,1
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,None,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,None,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,None,S,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,None,S,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,None,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 요금을 기준으로 내림차순 정렬하고 상위 5명만 출력하세요.
</div>

In [86]:
joined_df2.sort_values('Fare', ascending=False)[:5]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
737,738,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,1,512.3292,B101,C,1
679,680,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,1,512.3292,B51 B53 B55,C,1
258,259,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,1,512.3292,None,C,1
438,439,"Fortune, Mr. Mark",male,64.0,1,4,19950,1,263.0000,C23 C25 C27,S,0
88,89,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,1,263.0000,C23 C25 C27,S,1

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별로 그룹화하여 생존률 평균을 구하세요.
</div>

In [92]:
joined_df2[['Sex', 'Survived']].groupby('Sex').mean()

        Survived
Sex
female  0.742038
male    0.188908

<div class="alert alert-success">
    <b>EXERCISE</b>: Pclass별 평균 나이를 구하세요.
</div>

In [94]:
joined_df2[['Pclass', 'Age']].groupby('Pclass').mean()

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'에 10을 더한 값을 새로운 컬럼 'Age_plus_10'으로 추가하세요.
</div>

In [96]:
joined_df2["Age_plus_10"] = joined_df2["Age"] + 10

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'가 18 이상이면 '성인', 아니면 '미성년'으로 분류하는 컬럼을 추가하세요.
</div>

In [185]:
joined_df2["isAdult"] = joined_df2["Age"].apply(lambda x:"성인" if x >= 18 else "미성년")
joined_df2

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isAdult
PassengerId,,,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,32.0,성인
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1,48.0,성인
3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,36.0,성인
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1,45.0,성인
5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0,37.0,성인
888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1,29.0,성인
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,NaN,3,23.4500,Unknown,S,0,NaN,성인
890,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1,36.0,성인
891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0,42.0,성인

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'의 결측치를 평균으로 채우세요.
</div>

In [137]:
joined_df2['Age'] = joined_df2['Age'].fillna(joined_df2['Age'].mean())

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Cabin' 컬럼의 결측치를 'Unknown'으로 채우세요.
</div>

In [186]:
joined_df2['Cabin'] = joined_df2['Cabin'].fillna('Unknown')
joined_df2['Cabin'].isna().sum()

np.int64(0)

<div class="alert alert-success">
    <b>EXERCISE</b>: 중복된 'Ticket' 값을 제거하고 몇 개가 남는지 출력하세요.
</div>

In [193]:
joined_df2["Ticket"] = joined_df2["Ticket"].drop_duplicates()
joined_df2["Ticket"]

PassengerId
1             A/5 21171
2              PC 17599
3      STON/O2. 3101282
4                113803
5                373450
             ...
887              211536
888              112053
889                 NaN
890              111369
891              370376
Name: Ticket, Length: 891, dtype: object

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Embarked' 컬럼의 고유값과 각각의 개수를 출력하세요.
</div>

In [192]:
joined_df2['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 'PassengerId'로 설정하세요.
</div>

In [144]:
joined_df2 = joined_df2.set_index("PassengerId")

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 초기화하세요.
</div>

In [145]:
joined_df2.reset_index(drop=True)

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10
0,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,32.0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1,48.0
2,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,36.0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1,45.0
4,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0,37.0
887,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1,29.0
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,NaN,3,23.4500,Unknown,S,0,NaN
889,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1,36.0
890,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0,42.0

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별과 Pclass의 생존률을 피벗 테이블로 만드세요.
</div>

In [146]:
joined_df2.pivot_table(values = "Survived", index="Sex", columns="Pclass")

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

<div class="alert alert-success">
    <b>EXERCISE</b>: groupby()를 사용하여 각 성별(sex)의 평균 나이(age)를 구하세요.
</div>

In [169]:
joined_df2[['Sex', 'Age']].groupby('Sex').mean()

              Age
Sex
female  28.216730
male    30.505824

<div class="alert alert-success">
    <b>EXERCISE</b>: 전체 승객(passenger)의 평균 생존율을 구하세요.
</div>

In [156]:
joined_df2["Survived"].mean()

np.float64(0.3838383838383838)

<div class="alert alert-success">
    <b>EXERCISE</b>: 25세 이하 승객의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [157]:
joined_df2[(joined_df2["Age"] <= 25) & (joined_df2["Sex"] <= "male")]["Survived"].mean()

np.float64(0.4119601328903654)

<div class="alert alert-success">
    <b>EXERCISE</b>: 남성의 생존율을 구하세요. 여성의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [161]:
joined_df2[["Sex", "Survived"]].groupby('Sex').mean()

        Survived
Sex
female  0.742038
male    0.188908

<div class="alert alert-success">
    <b>EXERCISE</b>: 생존율을 구하는 함수가 작성되어 있습니다. 성별 생존율을 groupby를 활용해 구하기 위해 ?부분을 알맞게 채워주세요.
</div>

In [195]:
def survival_ratio(survived):
    return survived.sum() / len(survived)

In [196]:
joined_df2[["Sex", "Survived"]].groupby('Sex').agg(survival_ratio)

        Survived
Sex
female  0.742038
male    0.188908