# 12지도학습_분류분석_KNN_SVM_포로모션_효율예측분석

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [2]:
mem = pd.read_csv("./data/member.csv")
tran = pd.read_csv("./data/transaction.csv")

In [3]:
mem.head()

       id  recency   zip_code  is_referral channel  conversion
0  906145       10  Surburban            0   Phone           0
1  184478        6      Rural            1     Web           0
2  394235        7  Surburban            1     Web           0
3  130152        9      Rural            1     Web           0
4  940352        2      Urban            0     Web           0

* 쇼핑몰 고객 데이터, 프로모션 쿠폰을 발행하고 사용 여부 데이터 수집
* mem : 고객id, 최근 방문일, 사는지역, 추천여부, 주요접속채널, 쿠폰 사용여부(target)
* tran : 고객id, 구매수량, 총 구매금액
* 전통적 마케팅 분석 방법 RFM 기법을 활용해 고객 데이터에서 파생변수를 생성 후 분석
* R: Recency : 현재일 - 최근 구매일
* F: Frequency : 구매빈도
* M : Monetary : 구매금액
* 종속변수 : conversion => 고객이 프로모션에 반응 했는가? 1=yes, 0=no

In [5]:
tran.head()

       id  num_item  total_amount
0  906145         5         34000
1  906145         1         27000
2  906145         4         33000
3  184478         4         29000
4  394235         4         33000

In [7]:
tran.isna().sum()

id              0
num_item        0
total_amount    0
dtype: int64

In [8]:
tran.describe()

                  id       num_item   total_amount
count  196836.000000  196836.000000  196836.000000
mean   550557.552932       3.078365   21837.102969
std    259254.795613       1.478408    8218.005565
min    100001.000000       1.000000    8000.000000
25%    326719.000000       2.000000   15000.000000
50%    550918.000000       3.000000   22000.000000
75%    774916.000000       4.000000   29000.000000
max    999997.000000       6.000000   38000.000000