In [3]:
import requests
import pandas as pd

# 자료 수집하기

In [9]:
for code in ori_data['소분류코드']:
    print(code)
    url = "http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
    payload = {'servicekey': '7V78PQCO+ycH8PsNQjW3Qt5lJ/b+7v6wSXIWFgRZEZB9w2PIR97FSFP/Gfy/v3MroRk2J7JykRUvaxOkpiQszQ==',
           'divId': 'indsSclsCd', "key":"code", "numOfRows": 1, "pageNo": 1000, "type":"json"}
    r = requests.get(url, params=payload)
    data = r.json()
    data

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
  'columns': ['상가업소번호',
   '상호명',
   '지점명',
   '상권업종대분류코드',
   '상권업종대분류명',
   '상권업종중분류코드',
   '상권업종중분류명',
   '상권업종소분류코드',
   '상권업종소분류명',
   '표준산업분류코드',
   '표준산업분류명',
   '시도코드',
   '시도명',
   '시군구코드',
   '시군구명',
   '행정동코드',
   '행정동명',
   '법정동코드',
   '법정동명',
   'PNU코드',
   '대지구분코드',
   '대지구분명',
   '지번본번지',
   '지번부번지',
   '지번주소',
   '도로명코드',
   '도로명',
   '건물본번지',
   '건물부번지',
   '건물관리번호',
   '건물명',
   '도로명주소',
   '구우편번호',
   '신우편번호',
   '동정보',
   '층정보',
   '호정보',
   '경도',
   '위도'],
  'stdrYm': '202412',
  'resultCode': '00',
  'resultMsg': 'NORMAL SERVICE'},
 'body': {'items': [{'bizesId': 'MA010120220800009839',
    'bizesNm': '매일치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110630',
    'adongNm': '종로5.6가동',
    'ldongCd': '1111016700',
    'ldongNm': '충신동',
    'lnoCd': '1111016700100510000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 51,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 종로구 충신동 51',
    'rdnmCd': '111104100223',
    'rdnm': '서울특별시 종로구 율곡로19길',
    'bldMnno': 9,
    'bldSlno': '',
    'bldMngNo': '1111016700100510000012087',
    'bldNm': '',
    'rdnmAdr': '서울특별시 종로구 율곡로19길 9',
    'oldZipcd': '110844',
    'newZipcd': '03100',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.005411172882,
    'lat': 37.5759981398728}],
  'numOfRows': 1,
  'pageNo': 6,
  'totalCount': 42095}}

# 수집한 자료 반복문으로 모으기

In [13]:
result = []
for i in range(1, 44):
    url = "http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
    payload = {'servicekey': '7V78PQCO+ycH8PsNQjW3Qt5lJ/b+7v6wSXIWFgRZEZB9w2PIR97FSFP/Gfy/v3MroRk2J7JykRUvaxOkpiQszQ==',
                'divId': 'indsSclsCd', "key":"I21006", "numOfRows": 1000, "pageNo": i, "type":"json"}
    r = requests.get(url, params=payload)
    data = r.json()
    result.append(data)

In [10]:
data["body"]["numOfRows"] * data["body"]["pageNo"]

1

In [53]:
result[0]

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
  'columns': ['상가업소번호',
   '상호명',
   '지점명',
   '상권업종대분류코드',
   '상권업종대분류명',
   '상권업종중분류코드',
   '상권업종중분류명',
   '상권업종소분류코드',
   '상권업종소분류명',
   '표준산업분류코드',
   '표준산업분류명',
   '시도코드',
   '시도명',
   '시군구코드',
   '시군구명',
   '행정동코드',
   '행정동명',
   '법정동코드',
   '법정동명',
   'PNU코드',
   '대지구분코드',
   '대지구분명',
   '지번본번지',
   '지번부번지',
   '지번주소',
   '도로명코드',
   '도로명',
   '건물본번지',
   '건물부번지',
   '건물관리번호',
   '건물명',
   '도로명주소',
   '구우편번호',
   '신우편번호',
   '동정보',
   '층정보',
   '호정보',
   '경도',
   '위도'],
  'stdrYm': '202412',
  'resultCode': '00',
  'resultMsg': 'NORMAL SERVICE'},
 'body': {'items': [{'bizesId': 'MA010120220800445252',
    'bizesNm': '가마로닭강정',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590605',
    'adongNm': '흑석동',
    'ldongCd': '1159010500',
    'ldongNm': '흑석동',
    'lnoCd': '1159010500102250015',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 225,
    'lnoSlno': 15,
    'lnoAdr': '서울특별시 동작구 흑석동 225-15',
    'rdnmCd': '115903119006',
    'rdnm': '서울특별시 동작구 서달로',
    'bldMnno': 151,
    'bldSlno': '',
    'bldMngNo': '1159010500102240001017670',
    'bldNm': '제',
    'rdnmAdr': '서울특별시 동작구 서달로 151',
    'oldZipcd': '156861',
    'newZipcd': '06973',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.961534642074,
    'lat': 37.5069754179478},
   {'bizesId': 'MA010120220800445378',
    'bizesNm': '수원왕갈비통닭',
    'brchNm': '보라매점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56213',
    'ksicNm': '생맥주 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590660',
    'adongNm': '대방동',
    'ldongCd': '1159010800',
    'ldongNm': '대방동',
    'lnoCd': '1159010800104150051',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 415,
    'lnoSlno': 51,
    'lnoAdr': '서울특별시 동작구 대방동 415-51',
    'rdnmCd': '115904157550',
    'rdnm': '서울특별시 동작구 여의대방로24가길',
    'bldMnno': 12,
    'bldSlno': '',
    'bldMngNo': '1159010800104150005004103',
    'bldNm': '',
    'rdnmAdr': '서울특별시 동작구 여의대방로24가길 12',
    'oldZipcd': '156811',
    'newZipcd': '07055',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.921008197327,
    'lat': 37.4987741397009},
   {'bizesId': 'MA010120220800430361',
    'bizesNm': '페리카나',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590651',
    'adongNm': '사당5동',
    'ldongCd': '1159010700',
    'ldongNm': '사당동',
    'lnoCd': '1159010700102130007',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 213,
    'lnoSlno': 7,
    'lnoAdr': '서울특별시 동작구 사당동 213-7',
    'rdnmCd': '115903119004',
    'rdnm': '서울특별시 동작구 사당로',
    'bldMnno': 168,
    'bldSlno': '',
    'bldMngNo': '1159010700102130007006364',
    'bldNm': '',
    'rdnmAdr': '서울특별시 동작구 사당로 168',
    'oldZipcd': '156879',
    'newZipcd': '07030',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.967571599142,
    'lat': 37.4868127026347},
   {'bizesId': 'MA010120220800445715',
    'bizesNm': '치킨89',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590680',
    'adongNm': '신대방2동',
    'ldongCd': '1159010900',
    'ldongNm': '신대방동',
    'lnoCd': '1159010900103460008',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 346,
    'lnoSlno': 8,
    'lnoAdr': '서울특별시 동작구 신대방동 346-8',
    'rdnmCd': '115903005078',
    'rdnm': '서울특별시 동작구 보라매로',
    'bldMnno': 98,
    'bldSlno': 5,
    'bldMngNo': '1159010900103460008001825',
    'bldNm': '노블레스빌',
    'rdnmAdr': '서울특별시 동작구 보라매로 98-5',
    'oldZipcd': '156847',
    'newZipcd': '07053',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.92848410058,
    'lat': 37.497931956184},
   {'bizesId': 'MA010120220800439275',
    'bizesNm': '또바기치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11560',
    'signguNm': '영등포구',
    'adongCd': '11560650',
    'adongNm': '신길3동',
    'ldongCd': '1156013200',
    'ldongNm': '신길동',
    'lnoCd': '1156013200103470294',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 347,
    'lnoSlno': 294,
    'lnoAdr': '서울특별시 영등포구 신길동 347-294',
    'rdnmCd': '115603000023',
    'rdnm': '서울특별시 영등포구 가마산로',
    'bldMnno': 439,
    'bldSlno': '',
    'bldMngNo': '1156013200103470294013808',
    'bldNm': '',
    'rdnmAdr': '서울특별시 영등포구 가마산로 439',
    'oldZipcd': '150848',
    'newZipcd': '07382',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.905292040295,
    'lat': 37.5053219054654},
   {'bizesId': 'MA010120220800445910',
    'bizesNm': '메이카페',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590530',
    'adongNm': '상도1동',
    'ldongCd': '1159010200',
    'ldongNm': '상도동',
    'lnoCd': '1159010200100070059',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 7,
    'lnoSlno': 59,
    'lnoAdr': '서울특별시 동작구 상도동 7-59',
    'rdnmCd': '115903119010',
    'rdnm': '서울특별시 동작구 흑석로',
    'bldMnno': 23,
    'bldSlno': '',
    'bldMngNo': '1159010200100070059029163',
    'bldNm': '',
    'rdnmAdr': '서울특별시 동작구 흑석로 23',
    'oldZipcd': '156830',
    'newZipcd': '06912',
    'dongNo': '',
    'flrNo': '2',
    'hoNo': '',
    'lon': 126.953302121467,
    'lat': 37.5050983596393},
   {'bizesId': 'MA010120220800445998',
    'bizesNm': '호치킨하우스',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590670',
    'adongNm': '신대방1동',
    'ldongCd': '1159010900',
    'ldongNm': '신대방동',
    'lnoCd': '1159010900106910026',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 691,
    'lnoSlno': 26,
    'lnoAdr': '서울특별시 동작구 신대방동 691-26',
    'rdnmCd': '115904157498',
    'rdnm': '서울특별시 동작구 신대방길',
    'bldMnno': 25,
    'bldSlno': '',
    'bldMngNo': '1159010900106910026034236',
    'bldNm': '',
    'rdnmAdr': '서울특별시 동작구 신대방길 25',
    'oldZipcd': '156854',
    'newZipcd': '07070',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.911103183778,
    'lat': 37.4879910593668},
   {'bizesId': 'MA010120220800446078',
    'bizesNm': '딥테이스트치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590510',
    'adongNm': '노량진1동',
    'ldongCd': '1159010100',
    'ldongNm': '노량진동',
    'lnoCd': '1159010100103250004',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 325,
    'lnoSlno': 4,
    'lnoAdr': '서울특별시 동작구 노량진동 325-4',
    'rdnmCd': '115904157205',
    'rdnm': '서울특별시 동작구 만양로3길',
    'bldMnno': 20,
    'bldSlno': '',
    'bldMngNo': '1159010100103250004033177',
    'bldNm': '신동아리버파크빌',
    'rdnmAdr': '서울특별시 동작구 만양로3길 20',
    'oldZipcd': '156813',
    'newZipcd': '06926',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.945880703427,
    'lat': 37.5081946499037},
   {'bizesId': 'MA010120220800446109',
    'bizesNm': '보드람치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590630',
    'adongNm': '사당2동',
    'ldongCd': '1159010700',
    'ldongNm': '사당동',
    'lnoCd': '1159010700101450029',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 145,
    'lnoSlno': 29,
    'lnoAdr': '서울특별시 동작구 사당동 145-29',
    'rdnmCd': '115904157119',
    'rdnm': '서울특별시 동작구 동작대로27가길',
    'bldMnno': 35,
    'bldSlno': '',
    'bldMngNo': '1159010700101450029034099',
    'bldNm': '명칭없음',
    'rdnmAdr': '서울특별시 동작구 동작대로27가길 35',
    'oldZipcd': '156816',
    'newZipcd': '07008',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.981185384489,
    'lat': 37.4860588080555},
   {'bizesId': 'MA010120220800446565',
    'bizesNm': '밸런스에프앤비',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11650',
    'signguNm': '서초구',
    'adongCd': '11650621',
    'adongNm': '방배4동',
    'ldongCd': '1165010100',
    'ldongNm': '방배동',
    'lnoCd': '1165010100114210000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1421,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 서초구 방배동 1421',
    'rdnmCd': '116504163668',
    'rdnm': '서울특별시 서초구 동광로12가길',
    'bldMnno': 6,
    'bldSlno': '',
    'bldMngNo': '1165010100114210000010112',
    'bldNm': '호',
    'rdnmAdr': '서울특별시 서초구 동광로12가길 6',
    'oldZipcd': '137852',
    'newZipcd': '06565',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.984633663019,
    'lat': 37.4875910206836},
   {'bizesId': 'MA010120220800422955',
    'bizesNm': '좌충우돌닭강정',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590520',
    'adongNm': '노량진2동',
    'ldongCd': '1159010100',
    'ldongNm': '노량진동',
    'lnoCd': '1159010100102310137',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 231,
    'lnoSlno': 137,
    'lnoAdr': '서울특별시 동작구 노량진동 231-137',
    'rdnmCd': '115903119008',
    'rdnm': '서울특별시 동작구 장승배기로',
    'bldMnno': 137,
    'bldSlno': '',
    'bldMngNo': '1159010100102310137030584',
    'bldNm': '',
    'rdnmAdr': '서울특별시 동작구 장승배기로 137',
    'oldZipcd': '156803',
    'newZipcd': '06935',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.939986802006,
    'lat': 37.5098046008},
   {'bizesId': 'MA010120220800423188',
    'bizesNm': '둘둘치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11140',
    'signguNm': '중구',
    'adongCd': '11140605',
    'adongNm': '을지로동',
    'ldongCd': '1114015000',
    'ldongNm': '을지로4가',
    'lnoCd': '1114015000103090002',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 309,
    'lnoSlno': 2,
    'lnoAdr': '서울특별시 중구 을지로4가 309-2',
    'rdnmCd': '111404103242',
    'rdnm': '서울특별시 중구 을지로20길',
    'bldMnno': 8,
    'bldSlno': '',
    'bldMngNo': '1114015000103160006012405',
    'bldNm': '',
    'rdnmAdr': '서울특별시 중구 을지로20길 8',
    'oldZipcd': '100849',
    'newZipcd': '04549',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.995268682542,
    'lat': 37.566060191354},
   {'bizesId': 'MA010120220800440008',
    'bizesNm': '헬로우치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590640',
    'adongNm': '사당3동',
    'ldongCd': '1159010700',
    'ldongNm': '사당동',
    'lnoCd': '1159010700111330000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1133,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 동작구 사당동 1133',
    'rdnmCd': '115904157269',
    'rdnm': '서울특별시 동작구 사당로23바길',
    'bldMnno': 9,
    'bldSlno': '',
    'bldMngNo': '1159010700111330000009210',
    'bldNm': '삼성래미안아파트',
    'rdnmAdr': '서울특별시 동작구 사당로23바길 9',
    'oldZipcd': '156776',
    'newZipcd': '07002',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.96918734896,
    'lat': 37.4896062595415},
   {'bizesId': 'MA010120220800446743',
    'bizesNm': '굽네치킨사당1동점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590620',
    'adongNm': '사당1동',
    'ldongCd': '1159010700',
    'ldongNm': '사당동',
    'lnoCd': '1159010700110380012',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1038,
    'lnoSlno': 12,
    'lnoAdr': '서울특별시 동작구 사당동 1038-12',
    'rdnmCd': '115904157277',
    'rdnm': '서울특별시 동작구 사당로26길',
    'bldMnno': 127,
    'bldSlno': '',
    'bldMngNo': '1159010700110380012011661',
    'bldNm': '',
    'rdnmAdr': '서울특별시 동작구 사당로26길 127',
    'oldZipcd': '156826',
    'newZipcd': '07025',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.978146132924,
    'lat': 37.4781834676937},
   {'bizesId': 'MA010120220800423757',
    'bizesNm': '페리카나치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11560',
    'signguNm': '영등포구',
    'adongCd': '11560650',
    'adongNm': '신길3동',
    'ldongCd': '1156013200',
    'ldongNm': '신길동',
    'lnoCd': '1156013200103250096',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 325,
    'lnoSlno': 96,
    'lnoAdr': '서울특별시 영등포구 신길동 325-96',
    'rdnmCd': '115604154019',
    'rdnm': '서울특별시 영등포구 가마산로61길',
    'bldMnno': 3,
    'bldSlno': 1,
    'bldMngNo': '1156013200103250096013802',
    'bldNm': '',
    'rdnmAdr': '서울특별시 영등포구 가마산로61길 3-1',
    'oldZipcd': '150848',
    'newZipcd': '07382',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.90520120912,
    'lat': 37.505601144147},
   {'bizesId': 'MA010120220800423994',
    'bizesNm': '페리카나치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11560',
    'signguNm': '영등포구',
    'adongCd': '11560630',
    'adongNm': '신길1동',
    'ldongCd': '1156013200',
    'ldongNm': '신길동',
    'lnoCd': '1156013200104510001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 451,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 영등포구 신길동 451-1',
    'rdnmCd': '115604154754',
    'rdnm': '서울특별시 영등포구 영등포로86길',
    'bldMnno': 12,
    'bldSlno': '',
    'bldMngNo': '1156013200104510001017145',
    'bldNm': '',
    'rdnmAdr': '서울특별시 영등포구 영등포로86길 12',
    'oldZipcd': '150051',
    'newZipcd': '07354',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.923086714073,
    'lat': 37.5120383061212},
   {'bizesId': 'MA010120220800431863',
    'bizesNm': '비비큐',
    'brchNm': '사당점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590620',
    'adongNm': '사당1동',
    'ldongCd': '1159010700',
    'ldongNm': '사당동',
    'lnoCd': '1159010700110300003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1030,
    'lnoSlno': 3,
    'lnoAdr': '서울특별시 동작구 사당동 1030-3',
    'rdnmCd': '115904157166',
    'rdnm': '서울특별시 동작구 동작대로9길',
    'bldMnno': 7,
    'bldSlno': '',
    'bldMngNo': '1159010700110300003010584',
    'bldNm': '',
    'rdnmAdr': '서울특별시 동작구 동작대로9길 7',
    'oldZipcd': '156826',
    'newZipcd': '07015',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.981085017435,
    'lat': 37.4805265988115},
   {'bizesId': 'MA010120220800440367',
    'bizesNm': '훌랄라숯불바베큐',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11560',
    'signguNm': '영등포구',
    'adongCd': '11560585',
    'adongNm': '도림동',
    'ldongCd': '1156011800',
    'ldongNm': '도림동',
    'lnoCd': '1156011800101130018',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 113,
    'lnoSlno': 18,
    'lnoAdr': '서울특별시 영등포구 도림동 113-18',
    'rdnmCd': '115604154317',
    'rdnm': '서울특별시 영등포구 도신로29길',
    'bldMnno': 6,
    'bldSlno': '',
    'bldMngNo': '1156011800101130018026409',
    'bldNm': '훌랄라숯불바베큐',
    'rdnmAdr': '서울특별시 영등포구 도신로29길 6',
    'oldZipcd': '150829',
    'newZipcd': '07368',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.90529862666,
    'lat': 37.5090610802702},
   {'bizesId': 'MA010120220800448025',
    'bizesNm': '교촌치킨노량진점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',
    'signguNm': '동작구',
    'adongCd': '11590520',
    'adongNm': '노량진2동',
    'ldongCd': '1159010100',
    'ldongNm': '노량진동',
    'lnoCd': '1159010100100370001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 37,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 동작구 노량진동 37-1',
    'rdnmCd': '115904157083',
    'rdnm': '서울특별시 동작구 노량진로8길',
    'bldMnno': 55,
    'bldSlno': '',
    'bldMngNo': '1159010100100370006030350',
    'bldNm': '더클래식동작',
    'rdnmAdr': '서울특별시 동작구 노량진로8길 55',
    'oldZipcd': '156052',
    'newZipcd': '06928',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.938570893242,
    'lat': 37.5123717351872},
   {'bizesId': 'MA010120220800448335',
    'bizesNm': '미스터짱닭',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11590',

In [57]:
result3 = {}
for page in result:
    for item in page["body"]["items"]:
        for key, value in zip(page["header"]["columns"], item.values()):
            result3.setdefault(key, []).append(value)

In [58]:
df = pd.DataFrame(result3)
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220800445252,가마로닭강정,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1159010500102240001017670,제,서울특별시 동작구 서달로 151,156861,06973,,1,,126.961535,37.506975
1,MA010120220800445378,수원왕갈비통닭,보라매점,I2,음식,I210,기타 간이,I21006,치킨,I56213,...,1159010800104150005004103,,서울특별시 동작구 여의대방로24가길 12,156811,07055,,1,,126.921008,37.498774
2,MA010120220800430361,페리카나,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1159010700102130007006364,,서울특별시 동작구 사당로 168,156879,07030,,,,126.967572,37.486813
3,MA010120220800445715,치킨89,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1159010900103460008001825,노블레스빌,서울특별시 동작구 보라매로 98-5,156847,07053,,,,126.928484,37.497932
4,MA010120220800439275,또바기치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1156013200103470294013808,,서울특별시 영등포구 가마산로 439,150848,07382,,,,126.905292,37.505322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42090,MA0106202410A0530080,다사랑치킨,에코시티점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4511312200113300014000001,,전북특별자치도 전주시 덕진구 세병2길 32-18,561302,55149,,1,,127.125791,35.872366
42091,MA0106202410A0842347,푸라닭이천,마장점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4150034021102830015036863,,경기도 이천시 마장면 오천로 33,467814,17387,,,,127.352308,37.253954
42092,MA0106202410A0741260,보드람치킨,쌍용점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4413310700108230000055345,,충청남도 천안시 서북구 쌍용대로 119,331949,31149,,1,,127.132527,36.808137
42093,MA0106202410A2090834,찐이야숯불치킨,태전점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,2723012600102540030045203,,대구광역시 북구 태전로 53,702863,41456,,1,,128.543405,35.925012
42094,MA0106202410A1372857,비에이치치킨,여의도점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,1156011000100440013031502,충무빌딩,서울특별시 영등포구 여의대방로69길 7,150890,07333,,,,126.931257,37.519765

In [60]:
df.to_csv("공공데이터_상권정보_202504.csv", encoding="utf-8", index=False)

In [64]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [70]:
ori_data = pd.read_excel("./data/소상공인시장진흥공단_상가(상권)정보_업종분류(2302)_및_연계표_v1.0.xlsx", engine="openpyxl", header=[1])
ori_data

    대분류코드          대분류명 중분류코드              중분류명   소분류코드            소분류명
0      G2           소매업  G202  자동차 부품 및 내장품 소매업  G20201         타이어 소매업
1      G2           소매업  G202  자동차 부품 및 내장품 소매업  G20202      자동차 부품 소매업
2      G2           소매업  G203    모터사이클 및 부품 소매업  G20301  모터사이클 및 부품 소매업
3      G2           소매업  G204            종합 소매업  G20404            슈퍼마켓
4      G2           소매업  G204            종합 소매업  G20405             편의점
..    ...           ...   ...               ...     ...             ...
242    S2  수리 및 개인 서비스업  S209               세탁업  S20902          셀프 빨래방
243    S2  수리 및 개인 서비스업  S210    장례식장 및 관련 서비스업  S21001            장례식장
244    S2  수리 및 개인 서비스업  S210    장례식장 및 관련 서비스업  S21002      화장터/묘지/납골당
245    S2  수리 및 개인 서비스업  S211          기타 개인서비스  S21101            예식장업
246    S2  수리 및 개인 서비스업  S211          기타 개인서비스  S21105      결혼 상담 서비스업

[247 rows x 6 columns]

G20201
G20202
G20301
G20404
G20405
G20499
G20501
G20502
G20503
G20504
G20505
G20506
G20507
G20508
G20509
G20601
G20602
G20603
G20604
G20701
G20801
G20802
G20803
G20901
G20902
G20903
G20904
G20905
G20906
G20907
G20908
G20909
G20910
G20911
G21001
G21002
G21003
G21099
G21101
G21201
G21202
G21203
G21301
G21302
G21303
G21304
G21305
G21306
G21401
G21402
G21403
G21501
G21502
G21503
G21601
G21602
G21603
G21701
G21801
G21802
G21901
G22001
G22199
G22201
I10101
I10102
I10103
I10104
I10201
I10299
I20101
I20102
I20103
I20104
I20105
I20106
I20107
I20108
I20109
I20110
I20111
I20112
I20113
I20199
I20201
I20202
I20301
I20302
I20303
I20399
I20401
I20402
I20403
I20499
I20501
I20599
I20601
I20701
I20702
I21001
I21002
I21003
I21004
I21005
I21006
I21007
I21008
I21099
I21101
I21102
I21103
I21104
I21201
L10203
M10301
M10302
M10303
M10306
M10307
M10399
M10401
M10402
M10499
M10501
M10502
M10503
M10504
M10599
M10601
M10703
M10901
M10902
M10903
M10904
M10999
M11101
M11201
M11202
M11203
M11204
M11301
M11401
M11502
M11504
N10101
N10201
N10202
N10203
N10301
N10401
N10402
N10403
N10501
N10599
N10703
N10799
N10802
N10805
N10901
N10999
N11001
N11002
N11003
N11004
N11099
N11101
N11102
N11199
P10501
P10601
P10603
P10605
P10607
P10609
P10611
P10613
P10615
P10617
P10619
P10621
P10623
P10625
P10627
P10629
P10701
P10799
Q10101
Q10102
Q10103
Q10104
Q10105
Q10201
Q10202
Q10203
Q10204
Q10205
Q10206
Q10207
Q10208
Q10209
Q10210
Q10211
Q10212
Q10402
R10202
R10306
R10307
R10308
R10309
R10310
R10311
R10312
R10313
R10314
R10316
R10402
R10404
R10405
R10406
R10407
R10408
R10409
R10410
R10414
R10499
S20101
S20201
S20301
S20302
S20401
S20501
S20601
S20602
S20603
S20699
S20701
S20702
S20703
S20801
S20802
S20803
S20901
S20902
S21001
S21002
S21101
S21105